export const columnDefs = [
  {
    headerName: "ID",
    field: "id",
    filter: "agNumberColumnFilter",
    sortable: true,
    resizable: true,
    width: 100,
  },
  {
    headerName: "Name",
    field: "name",
    filter: "agTextColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
  },
  {
    headerName: "Age",
    field: "age",
    filter: "agNumberColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
    valueFormatter: (params: any) => params.value.toLocaleString(),
  },
  {
    headerName: "Active",
    field: "isActive",
    filter: "agBooleanColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
    cellRenderer: (params: any) => (params.value ? "✔️" : "❌"),
    cellEditor: "agCheckboxCellEditor",
  },
  {
    headerName: "Joined Date",
    field: "joined",
    filter: "agDateColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
    valueFormatter: (params: any) =>
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Balance ($)",
    field: "balance",
    filter: "agNumberColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
    valueFormatter: (params: any) => `$${params.value.toFixed(2)}`,
  },
  {
    headerName: "Email",
    field: "email",
    filter: "agTextColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
  },
  {
    headerName: "Score",
    field: "score",
    filter: "agNumberColumnFilter",
    sortable: true,
    resizable: true,
    editable: true,
    valueFormatter: (params: any) => params.value.toFixed(2),
  },
  {
    headerName: "Actions",
    field: "actions",
    cellRenderer: (params: any) => {
      return `<button onClick="alert('Edit ${params.data.id}')">✏️ Edit</button>
              <button onClick="alert('Delete ${params.data.id}')">🗑️ Delete</button>`;
    },
  },
];
